# Generated by Django 3.1 on 2020-10-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201025_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movieUrl',
            field=models.URLField(default='imdb.com'),
        ),
    ]
