# Generated by Django 3.1 on 2020-10-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_movie_movieurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbUrl',
            field=models.URLField(default='https://imdb.com'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieUrl',
            field=models.URLField(default='https://imdb.com'),
        ),
    ]
