# Generated by Django 3.1 on 2020-10-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201026_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtubeUrl',
            field=models.URLField(default='https://imdb.com'),
        ),
    ]
